### ISSUE TITLE
Docs should be clearer about debug flag

### ISSUE THREAD

**Issue by madsen** [rjbs/Log-Dispatchouli#12]
This is a follow-up to [RT#77622](https://rt.cpan.org/Public/Bug/Display.html?id=77622).  The issue there is that `$log->log_debug('message')` and `$log->log({level => 'debug'}, 'message')` are not equivalent.  The first is suppressed by the debug flag, and the second is not.

You stated that you are satisfied with that behavior, and I'm ok with that.  I have to agree that a careful reading of the documentation does support the position that the debug flag is only relevant to `log_debug`, not `log`.

But you shouldn't need to read the docs that closely.  The documentation for `log` should clearly state that it logs all messages regardless of level, and does not consult the debug flag.

On a side note, the Proxy docs have a bug: it says "(**bug** to the 'debug' logging level)" when you meant "**but**" (or possibly just delete that word altogether).

**Comment by rjbs** [comment]
Thanks, I believe these are both addressed now.
